apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    name: vpa-admission-controller
  name: vpa-admission-controller
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    name: vpa-admission-controller
  sessionAffinity: None
  type: ClusterIP
