apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations: {}
  labels:
    name: system-evictioner
  name: system:evictioner
rules:
  - apiGroups:
      - apps
      - extensions
    resources:
      - replicasets
    verbs:
      - get
  - apiGroups:
      - ''
    resources:
      - pods/eviction
    verbs:
      - create
