= Parameters

The parent key for all of the following parameters is `vertical_pod_autoscaler`.

== `namespace`

[horizontal]
type:: string
default:: `syn-vertical-pod-autoscaler`

The namespace in which to deploy this component.

== `images`

[horizontal]
type:: dictionary
default:: https://github.com/projectsyn/component-vertical-pod-autoscaler/blob/master/class/defaults.yml[See class/defaults.yml]

A dictionary of images used by this component.

== `allow_autoscaling`

[horizontal]
type:: boolean
default:: false

Wether to enable ability to actively update resources.

Enabling will also deploy the admission-controller and updater, so the component is able to actively update resources with its recommendations.

== `recommender_args`

[horizontal]
type:: Array
default:: []

Additional arguments for recommender.

See https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/FAQ.md#what-are-the-parameters-to-vpa-recommender[FAQ] for possible options.

== `updater_args`

[horizontal]
type:: Array
default:: []

Additional arguments for recommender.

See https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/FAQ.md#what-are-the-parameters-to-vpa-updater[FAQ] for possible options.

== `autoscaler`

[horizontal]
type:: string
default:: {}

Create autoscaler resources.

=== Example

[source,yaml]
----
autoscaler:
  my-namespace/frontend: {} <1>
  my-namespace/backend: <2>
    kind: StatefulSet
  my-other-namespace/database: <3>
    kind: StatefulSet
    mode: Auto
    spec: <4>
----
<1> Creates a autoscaler resource in namespace `my-namespace` for `Deployment` `frontend`.
<2> Creates a autoscaler resource in namespace `my-namespace` for `StatefulSet` `backend`.
<3> Creates a autoscaler resource in namespace `my-other-namespace` for `StatefulSet` `database`, and will automatically adjust resources.
<4> Add arbitrary https://cloud.google.com/kubernetes-engine/docs/concepts/verticalpodautoscaler[autoscaler specs].

For more information about `mode`, see https://github.com/kubernetes/design-proposals-archive/blob/main/autoscaling/vertical-pod-autoscaler.md#update-policy[UpdateMode].
